"""pod_gen_batch.py — 0.3 driver overlay: async confirms + g0 import.

GENERATED by blobkit.deploy_tools.make_bundle when sim_backend="gpu_batch".
pod_gen.py stays BYTE-VERBATIM (fleet-certified); this overlay adds two
driver conveniences around it (island_config flags, both default OFF; NO
science changes — jobs still run the locked ladder via pod_worker_batch):

  confirms="async"   pod_run_batch.sh merges gen N's pending s2/s3/lane
                     confirm shards INTO gen N+1's screen batch (one
                     run_assay_batch sweep per gen instead of 3-phase
                     serialization). Elites enter the block library one gen
                     late — MAP-Elites is order-tolerant and the CPU fleet
                     already had confirm lag. Implemented here as a shard
                     concatenator: `collect <gen>` moves every pending
                     s2g<N>/s3g<N>/laneg<N> shard into one combined jobs
                     file beside g<gen>'s shards (pod_worker_batch groups
                     them into tensors by (L, grid) automatically; seeds
                     are per-lane).

  g0="import"        `g0import <archive.json>` seeds the island archive
                     from a fully-confirmed donor archive (T_used stamps
                     kept, seed2_ok/seed3_ok kept) and marks gen 0 done, so
                     breeding starts at g1 with zero local g0 evals.
                     (Controller pre-confirms union5 ONCE on pod1, ships the
                     archive to pods 2-6.)

Usage:
  python3 pod_gen_batch.py collect <gen>            (confirms=async only)
  python3 pod_gen_batch.py g0import <archive.json>  (g0=import only)
Everything else (init/breed/ingest/ingest2/ingest3/lanes/status) is
pod_gen.py, unchanged.
"""
import glob, json, os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import pod_lib as PL


def collect(gen, cfg):
    """Move pending confirm shards (s2/s3/lane, any earlier gen) into the
    gen's combined batch dir. Returns list of shard paths for the sweep:
    g<gen> screens + all pending confirms. Idempotent: pod_worker_batch's
    done_set skips rows already evaluated."""
    P = PL.paths(cfg)
    shards = sorted(glob.glob(os.path.join(P["jobs"], f"g{gen}_w*.json")))
    pending = []
    for tag in ("s2g", "s3g", "laneg"):
        for p in sorted(glob.glob(os.path.join(P["jobs"], f"{tag}*_w*.json"))):
            base = os.path.basename(p)
            gnum = base.split("_w")[0].replace(tag, "")
            try:
                if int(gnum) < gen:            # earlier gens' confirms
                    pending.append(p)
            except ValueError:
                continue
    out = shards + pending
    manifest = os.path.join(P["jobs"], f"batch_g{gen}.json")
    json.dump(out, open(manifest, "w"), indent=1)
    print(f"batch_g{gen}: {len(shards)} screen shards "
          f"+ {len(pending)} pending confirm shards -> {manifest}", flush=True)
    for p in out:
        print(" ", p)
    return out


def g0import(archive_path, cfg):
    """Import a fully-confirmed archive as this island's g0-complete state."""
    P = PL.paths(cfg)
    src = json.load(open(archive_path))
    if os.path.exists(P["archive"]):
        cur = {}
        try:
            cur = json.load(open(P["archive"]))
        except Exception:
            pass
        if cur:
            raise SystemExit(f"archive {P['archive']} is non-empty "
                             f"({len(cur)} cells); g0import refuses to "
                             "overwrite (delete it first if intended)")
    n_conf = sum(1 for v in src.values()
                 if v.get("seed2_ok") and v.get("seed3_ok"))
    for v in src.values():
        v.setdefault("origin", "g0import")
        v.setdefault("first_gen", 0)
        v["gen"] = 0
    with PL.locked_json(P["archive"], {}) as c:
        c.data = src
        c.write()
    st = {}
    try:
        st = json.load(open(P["state"]))
    except Exception:
        pass
    st.setdefault("gen_stats", [])
    st["gen"] = 0
    st["g0_imported_from"] = os.path.abspath(archive_path)
    json.dump(PL.js(st), open(P["state"], "w"), indent=1)
    print(f"g0import: {len(src)} cells ({n_conf} fully confirmed) "
          f"from {archive_path}; breeding starts at g1", flush=True)


def main():
    cfg = PL.config()
    cmd = sys.argv[1]
    if cmd == "collect":
        if str(cfg.get("confirms", "sync")) != "async":
            raise SystemExit("collect requires island_config confirms='async'")
        collect(int(sys.argv[2]), cfg)
    elif cmd == "g0import":
        if str(cfg.get("g0", "eval")) != "import":
            raise SystemExit("g0import requires island_config g0='import'")
        g0import(sys.argv[2], cfg)
    else:
        raise SystemExit(f"unknown cmd {cmd} (collect | g0import)")


if __name__ == "__main__":
    main()
