"""pod_worker_batch.py — evaluate a jobs shard set BATCHED (blobkit 0.3).

GENERATED by blobkit.deploy_tools.make_bundle when sim_backend="gpu_batch".
One call = one tag's WHOLE job set through run_assay_batch: all lanes ride
ONE (B, nf_max, N, N) device tensor down the locked adaptive-horizon ladder
(rung-synchronized; per-lane t0 floors / caps from the job dicts), instead
of one world per process. Emits rows IDENTICAL to pod_worker.py's
pod_lib.evaluate rows (same funnel prefilter, same size caps, same status
vocabulary, same archive fields) plus lane/batched/provenance metadata from
assay_batch.

Usage: pod_worker_batch.py <shard.json> [<shard2.json> ...]
       (pod_run.sh batch mode passes ALL shards of a tag in one call; the
       results file is the dedup/idempotency layer, same as pod_worker.)

Grouping: jobs are grouped by (L, seed) and greedily packed into batches of
<= BMAX lanes (config "batch_lanes", default 32; per-batch B pads to
{4,8,16,32}). Jobs whose t0/cap don't sit on a shared doubling grid fall
back one group deeper (grid key). Funnel-rejected / size-capped jobs never
enter a batch (rows written directly, same as pod_worker).
"""
import json, os, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import pod_lib as PL

from blobkit import genome as G
from blobkit.assay_batch import run_assay_batch
from blobkit.assay_batch import nf_bucket as AB_nf_bucket   # [0.3.2]
import funnel as FU

BMAX_DEFAULT = 32


def done_set(P):
    try:
        rws = json.load(open(P["results"]))
    except Exception:
        return set()
    return {(r.get("cand"), r.get("phase")) for r in rws
            if r.get("kind") == "ds2_eval" and r.get("status") is not None}


def prefilter(job, cfg, P):
    """pod_lib.evaluate's pre-assay stages (verbatim rules): vtags, size cap,
    funnel. Returns (row, ready_genome|None); row is written iff not ready."""
    import ds2_ops as OPS2
    g = job["genome"]
    OPS2.ensure_vtags(g)
    seed = int(job.get("seed", cfg.get("seed", 1)))
    row = dict(kind="ds2_eval", phase=job.get("kind", "screen"),
               island=cfg.get("island"), cand=job["cand"], gen=job.get("gen"),
               op=job.get("op"), parents=job.get("parents"),
               params=job.get("params"), seed=seed, metrics="v2",
               sim_backend="gpu_batch", ghash=PL.ghash(g))
    na, nc = len(g["acts"]), len(g["chans"])
    row["na"], row["nc"] = na, nc
    row["n_bilin"] = len(g.get("bilin", []) or [])
    row["vtags"] = list(g.get("vtags", []) or [])
    row["minted"] = PL.minted_uids(g)
    if na > PL.MAX_ACT or na + nc > PL.MAX_FIELDS:
        row["status"] = "size_cap"
        PL.append_result(row, P["results"])
        return row, None
    t0w = time.time()
    fu = FU.funnel(g)
    row["funnel"] = dict(stage=fu["stage"], margin=fu.get("g0a_margin"))
    row["wall_funnel"] = round(time.time() - t0w, 3)
    if fu["stage"] != "pass":
        row["status"] = fu["stage"]
        row["genome"] = G.genome_json(g)
        PL.append_result(row, P["results"])
        return row, None
    return row, g


def grid_key(job, cfg):
    """Batch-compat key. Seeds are PER-LANE (init_soup_gpu_batch takes
    (genome, seed) pairs), so screens (s1) and s2/s3 confirm jobs share one
    tensor — the async-confirms mode rides on this. Split on: L (one grid N
    per tensor), the t0/cap doubling-grid class (fleet t0/cap values
    ({2500..20000, longH 40000}) are all 2500*2^k, so this rarely splits),
    and the nf PADDING BUCKET [0.3.2]: pack_genomes pads every lane to the
    call's nf_max, so mixed-nf calls make narrow worlds pay wide-world
    FLOPs (H100 V2 audit: 2-4x waste on union4-like mixes). One bucket =
    one run_assay_batch call."""
    L = float(job.get("L") or 128.0)
    t0 = float(job.get("t0") or 2500.0)
    cap = float(job.get("cap") or 20000.0)
    def _pow2_class(v, base=2500.0):
        r = v / base
        import math
        k = round(math.log2(r)) if r > 0 else -1
        return "grid" if (r > 0 and abs(r - 2 ** k) < 1e-9 and k >= 0) \
            else f"off_{v}"
    return (L, _pow2_class(t0), _pow2_class(cap),
            AB_nf_bucket(job["genome"]))


def expected_T(job):
    """Ladder-length prior for lane ordering [0.3.2]: confirm/lane jobs
    carry a t0 floor (seed1's T_used); screens default to the base rung.
    Sorting a bucket by DESCENDING expected T keeps likely-extenders
    adjacent, so after early rungs exit the survivors repack densely
    instead of being scattered across sparse tensors."""
    return (float(job.get("cap") or 0.0) if job.get("kind") == "lane"
            else float(job.get("t0") or 2500.0))


def flush_batch(batch, cfg, P):
    """One run_assay_batch call for a compatible group; write a row per lane."""
    if not batch:
        return
    jobs, rows = [], []
    for job, row in batch:
        jd = dict(genome=G.genome_json(job["genome"]),
                  seed=row["seed"],
                  t0=(float(job["t0"]) if job.get("t0") else None),
                  cap=(float(job["cap"]) if job.get("cap") else None))
        if job.get("_ic") is not None:      # [v3 pilot 2] ic lanes ride GPU
            jd["ic"] = job["_ic"]
            row["ic_merge"] = True
        jobs.append(jd)
        rows.append((job, row))
    kw = {}
    L = float(batch[0][0].get("L") or 128.0)
    npz_map = {i: os.path.join(P["runs"], f'{job["cand"]}.npz')
               for i, (job, _r) in enumerate(batch)}
    t1 = time.time()
    try:
        outs = run_assay_batch(jobs, dtype=str(cfg.get("batch_dtype", "f32")),
                               L=L, results_path=None, verbose=False,
                               battery_procs=int(cfg.get("battery_procs",
                                                         min(8, os.cpu_count() or 1))),
                               save_npz_map=npz_map, **kw)
    except ValueError:
        if len(batch) == 1:
            raise                    # single lane still bad: real error
        # incompatible ladder mix slipped a group: run lanes one by one
        for item in batch:
            flush_batch([item], cfg, P)
        return
    wall = round(time.time() - t1, 1)
    for i, ((job, row), out) in enumerate(zip(rows, outs)):
        hor = (out or {}).get("horizon") or {}
        why = hor.get("why_stopped")
        err = (out or {}).get("assay_error")
        row["wall_assay"] = wall            # batch wall (shared clock)
        row["lane"] = i
        row["batched"] = True
        if err is not None:
            msg = err
            if "non-empty vector" in msg or "empty slice" in msg:
                row["status"] = "no_blobs"
            else:
                row["status"] = "assay_error"
            row["error"] = msg[:300]
            row["interest"] = 0.0
            row["genome"] = G.genome_json(job["genome"])
            PL.append_result(row, P["results"])
            print(job["cand"], row["status"], flush=True)
            continue
        row.update(status=("blowup" if why == "blowup" else
                           "all_dead" if why == "all_dead" else "ok"),
                   interest=out.get("interest", 0.0),
                   T_used=hor.get("T_used"),
                   horizon=PL.lean_horizon(hor), flags=out.get("flags"),
                   summary=out.get("summary") or None)
        if out.get("battery_mode"):              # [0.3.4] subsampled flag
            row["battery_mode"] = out["battery_mode"]
        row["extended"] = bool(hor.get("n_extensions"))
        try:
            row["cell"] = PL.cell_key_v2(out)
        except Exception as e:
            row["cell"] = None
            row["cell_error"] = repr(e)[:200]
        # [v3 pilot 2] C9 rescore moved OFF the main thread: submit to the
        # spawn pool and defer append to drain_pending (GPU keeps sweeping).
        row["genome"] = G.genome_json(job["genome"])
        npz = npz_map.get(i)
        if npz and os.path.exists(npz):
            if RESCORE_POOL is not None:
                PENDING.append((row, npz,
                                RESCORE_POOL.submit(_rescore_task, npz,
                                                    float(row.get("interest") or 0.0))))
            else:                              # no pool: rescore inline (rare)
                _apply_rescore(row, npz,
                               _rescore_task(npz, float(row.get("interest") or 0.0)))
                PL.append_result(row, P["results"])
                print(job["cand"], row.get("status"), row.get("interest"),
                      row.get("cell"), f'T={row.get("T_used")}', flush=True)
        else:
            PL.append_result(row, P["results"])
            print(job["cand"], row.get("status"), row.get("interest"),
                  row.get("cell"), f'T={row.get("T_used")}', flush=True)




# ---------------------------------------------------------------- [v3 pilot 2]
# C9 rescore pool: spawn context (no inherited CUDA/JAX state), light imports
# in the task (v3_postpass+metrics_v3+numpy only — no jax in the child).
RESCORE_POOL = None
PENDING = []                      # (row, npz_path, future) awaiting C9 merge


def _rescore_task(npz_path, interest_v2):
    """Child-side: load rec npz, compute partial-mode C9 via v3_postpass.
    Returns the rescored field dict (or c9_error)."""
    import numpy as _np, sys as _sys, os as _os
    _here = _os.path.dirname(_os.path.abspath(__file__))
    for pth in (_here, _os.path.join(_here, "lib")):
        if pth not in _sys.path:
            _sys.path.insert(0, pth)
    import v3_postpass as V3P
    slim = {"interest": interest_v2}
    try:
        z = _np.load(npz_path, allow_pickle=True)
        if "run" not in z:
            slim["c9_error"] = "no run key in npz"
            return slim
        rec = dict(z["run"].item())
        V3P.rescore_row(slim, rec)
    except Exception as e:
        slim["c9_error"] = repr(e)[:120]
    return slim


def _apply_rescore(row, npz, slim):
    """Main-side: merge rescored fields, spatial-class cell axis, npz policy."""
    if slim:
        for k in ("C9", "C9_factors", "spatial_class", "c9_partial",
                  "interest_v2", "interest", "c9_error"):
            if k in slim:
                row[k] = slim[k]
        if row.get("cell") and row.get("spatial_class"):
            row["cell"] = row["cell"] + "|" + row["spatial_class"]
    if (row.get("interest") or 0.0) >= PL.NPZ_MIN_INTEREST:
        row["npz"] = os.path.basename(npz)
    else:
        try:
            os.remove(npz)
        except OSError:
            pass


def drain_pending(P, block=False):
    """Merge completed rescore futures into rows and append them."""
    global PENDING
    keep = []
    for row, npz, fut in PENDING:
        if not block and not fut.done():
            keep.append((row, npz, fut))
            continue
        try:
            slim = fut.result()
        except Exception as e:
            slim = {"c9_error": repr(e)[:120]}
        _apply_rescore(row, npz, slim)
        PL.append_result(row, P["results"])
        print(row.get("cand"), row.get("status"), row.get("interest"),
              row.get("cell"), f'T={row.get("T_used")}',
              "C9=%s" % row.get("C9"), flush=True)
    PENDING = keep


def eval_ic_jobs(ic_jobs, cfg, P):
    """[v3 pilot] FALLBACK (engine < 0.3.5): CPU assay_v3 path for spatial-IC
    merge lanes. With blobkit >= 0.3.5 ic lanes ride the GPU batch instead."""
    import numpy as _np
    sys.path.insert(0, os.path.join(HERE, "lib"))
    import assay_v3 as AV3
    import v3_postpass as V3P
    from concurrent.futures import ThreadPoolExecutor
    def _one(jr):
        job, row = jr
        _eval_single_ic(job, row, cfg, P)
    with ThreadPoolExecutor(max_workers=2) as _ex:
        list(_ex.map(_one, ic_jobs))
    return

def _eval_single_ic(job, row, cfg, P):
    import numpy as _np, time, os, sys
    sys.path.insert(0, os.path.join(HERE, "lib"))
    import assay_v3 as AV3
    import v3_postpass as V3P
    if True:
        g = job["genome"]
        ic = None
        icp = job.get("ic_npz")
        if icp and not os.path.isabs(icp):
            icp = os.path.join(HERE, icp)
        if icp and os.path.exists(icp):
            ic = _np.load(icp)["ic"]
        t0w = time.time()
        try:
            out = AV3.run_assay(g, seed=int(job.get("seed", cfg.get("seed", 1))),
                                workers=3, ic_override=ic, verbose=False,
                                t0=(float(job["t0"]) if job.get("t0") else AV3.T0_DEFAULT),
                                cap=(float(job["cap"]) if job.get("cap") else AV3.T_CAP))
        except Exception as e:
            row.update(status="assay_error", error=repr(e)[:300], interest=0.0,
                       genome=job["genome"])
            PL.append_result(row, P["results"])
            return
        hor = out.get("horizon") or {}
        why = hor.get("why_stopped")
        row.update(status=("blowup" if why == "blowup" else
                           "all_dead" if why == "all_dead" else "ok"),
                   interest=out.get("interest", 0.0),
                   T_used=hor.get("T_used"), horizon=PL.lean_horizon(hor),
                   flags=out.get("flags"), summary=out.get("summary") or None,
                   wall_assay=round(time.time() - t0w, 1), batched=False,
                   ic_merge=True)
        try:
            row["cell"] = PL.cell_key_v2(out)
        except Exception as e:
            row["cell"] = None; row["cell_error"] = repr(e)[:200]
        # assay_v3 already blends: out["interest"]=interest_v3, d9 carries C9
        d9 = (out.get("D") or {}).get("d9") or {}
        if d9:
            row["C9"] = float(d9.get("C9", 0.0))
            row["C9_factors"] = d9.get("factors")
            row["spatial_class"] = d9.get("spatial_class")
            row["c9_partial"] = bool(d9.get("partial", True))
            row["interest_v2"] = out.get("interest_v2")
            if row.get("cell") and row.get("spatial_class"):
                row["cell"] += "|" + row["spatial_class"]
        row["genome"] = job["genome"]
        PL.append_result(row, P["results"])
        print(job["cand"], "ic_merge", row["status"],
              round(row.get("interest", 0), 1), flush=True)

def main():
    cfg = PL.config()
    P = PL.paths(cfg)
    bmax = int(cfg.get("batch_lanes", BMAX_DEFAULT))
    # [0.3.3] gated record-path prototypes (perf thread; 2.18x claim row).
    # island_config: {"record_mode": "device"} -> devrec_proto (device-side
    # REC records; composes with {"apply_mode": "async"} -> asyncapply
    # drain). {"apply_mode": "async"} alone -> asyncapply_proto. Mirrors
    # perf/bench.py --devrec/--asyncapply wiring exactly.
    if cfg.get("record_mode") == "device":
        from blobkit.soup import devrec_proto as _DR
        _DR.install(async_apply=(cfg.get("apply_mode") == "async"),
                    procs=int(cfg["record_procs"])
                    if cfg.get("record_procs") else None)
        print("devrec_proto installed (record_mode=device, apply_mode="
              f"{cfg.get('apply_mode') or 'sync'})", flush=True)
    elif cfg.get("apply_mode") == "async":
        from blobkit.soup import asyncapply_proto as _AA
        _AA.install(procs=int(cfg["record_procs"])
                    if cfg.get("record_procs") else None)
        print("asyncapply_proto installed (apply_mode=async)", flush=True)
    # [v3 pilot 2] ic lanes ride the GPU batch when the engine has the
    # per-lane ic hook (blobkit >= 0.3.5: job dicts carry "ic"); C9 then
    # comes from the same rescore postpass as screens (partial mode) —
    # consistent scoring currency across screens/confirms/ic lanes.
    import blobkit as _BK
    ic_gpu = tuple(int(x) for x in
                   getattr(_BK, "__version__", "0").split(".")[:3]) >= (0, 3, 5)
    global RESCORE_POOL
    import multiprocessing as _mp
    from concurrent.futures import ProcessPoolExecutor as _PPE
    n_resc = int(cfg.get("rescore_procs", min(6, os.cpu_count() or 1)))
    if n_resc > 0:
        RESCORE_POOL = _PPE(max_workers=n_resc,
                            mp_context=_mp.get_context("spawn"))
    print(f"[v3 pilot 2] ic_gpu={ic_gpu} rescore_procs={n_resc}", flush=True)
    jobs = []
    for p in sys.argv[1:]:
        jobs += json.load(open(p))
    done = done_set(P)
    groups = {}
    for job in jobs:
        key = (job["cand"], job.get("kind", "screen"))
        if key in done:
            print("skip", key, flush=True)
            continue
        row, g = prefilter(job, cfg, P)
        if g is None:
            continue
        if job.get("ic_npz"):                      # [v3 pilot] spatial-IC lane
            if not ic_gpu:
                groups.setdefault("__ic__", []).append((job, row))
                continue
            import numpy as _np
            icp = job["ic_npz"]
            if not os.path.isabs(icp):
                icp = os.path.join(HERE, icp)
            if os.path.exists(icp):
                _ic = _np.load(icp)["ic"]
                _nf = len(job["genome"]["acts"]) + len(job["genome"]["chans"])
                if (_ic.ndim != 3 or _ic.shape[0] != _nf
                        or _ic.shape[1] != _ic.shape[2]):
                    row.update(status="assay_error", interest=0.0,
                               error=f"ic shape {_ic.shape} != nf={_nf} square",
                               genome=G.genome_json(job["genome"]))
                    PL.append_result(row, P["results"])
                    continue
                job["_ic"] = _ic
            else:
                row.update(status="assay_error", error=f"ic_npz missing: {icp}",
                           interest=0.0, genome=G.genome_json(job["genome"]))
                PL.append_result(row, P["results"])
                continue
        groups.setdefault(grid_key(job, cfg), []).append((job, row))
    ic_grp = groups.pop("__ic__", [])
    ic_thread = None
    if ic_grp:
        import threading
        # [v3 pilot fix] fallback path: ic lanes run CONCURRENTLY with the GPU
        # batch (CPU-bound vs GPU-bound) and 3-way parallel internally.
        ic_thread = threading.Thread(target=eval_ic_jobs,
                                     args=(ic_grp, cfg, P), daemon=True)
        ic_thread.start()
    for key in sorted(groups, key=str):
        grp = groups[key]
        # [0.3.2] descending expected T: likely-extenders stay adjacent ->
        # dense survivor repacks on the ladder's later rungs
        grp.sort(key=lambda jr: -expected_T(jr[0]))
        for i in range(0, len(grp), bmax):
            flush_batch(grp[i:i + bmax], cfg, P)
            drain_pending(P, block=False)   # cheap: merge whatever finished
    if ic_thread is not None:
        ic_thread.join()
    drain_pending(P, block=True)
    if RESCORE_POOL is not None:
        RESCORE_POOL.shutdown(wait=True)


if __name__ == "__main__":
    main()
